services:
  - type: web
    name: cloudflare-solver-api
    runtime: python
    runtimeVersion: '3.12'
    buildCommand: |
      apt-get update && apt-get install -y \
        chromium-browser \
        chromium-codecs-ffmpeg \
        libxss1 \
        libappindicator1 \
        libindicator7 \
        fonts-liberation \
        libnss3 \
        lsb-release \
        xdg-utils \
        libgbm1 \
        wget \
        && pip install --upgrade pip setuptools wheel \
        && pip install -r requirements.txt
    startCommand: uvicorn cf_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: PORT
        value: 8000
      - key: SB_NO_SANDBOX
        value: "true"
      - key: DISPLAY
        value: ":99"
